[ 2023-06-01 11:13:29,649 ] 186 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.2.9:5000
[ 2023-06-01 11:13:29,650 ] 186 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-06-01 11:14:17,250 ] 186 werkzeug - INFO - 127.0.0.1 - - [01/Jun/2023 11:14:17] "GET / HTTP/1.1" 200 -
[ 2023-06-01 11:14:17,467 ] 186 werkzeug - INFO - 127.0.0.1 - - [01/Jun/2023 11:14:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2023-06-01 11:16:41,480 ] 186 werkzeug - INFO - 127.0.0.1 - - [01/Jun/2023 11:16:41] "GET /predictdata HTTP/1.1" 200 -
[ 2023-06-01 11:17:08,554 ] 1414 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "E:\projects\MlProj\src\utils.py", line 58, in load_object
    with open(file_path, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\projects\MlProj\src\pipeline\predict_pipeline.py", line 17, in predict
    preprocessor=load_object(file_path=preprocessor_path)
  File "E:\projects\MlProj\src\utils.py", line 62, in load_object
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [E:\projects\MlProj\src\utils.py] line number [58] error message[[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\projects\MlProj\vvenv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\projects\MlProj\vvenv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\projects\MlProj\vvenv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\projects\MlProj\vvenv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "E:\projects\MlProj\src\pipeline\predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [E:\projects\MlProj\src\pipeline\predict_pipeline.py] line number [17] error message[Error occured in python script name [E:\projects\MlProj\src\utils.py] line number [58] error message[[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']]
[ 2023-06-01 11:17:08,564 ] 186 werkzeug - INFO - 127.0.0.1 - - [01/Jun/2023 11:17:08] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
